# Generated by Django 5.0.6 on 2025-07-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_water_tracker', models.BooleanField(default=True)),
                ('show_exercise_tracker', models.BooleanField(default=True)),
                ('show_meals_time', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('water_intake_ml', models.PositiveIntegerField(default=0)),
                ('exercises', models.ManyToManyField(blank=True, related_name='daily_logs', to='training.exercise')),
            ],
        ),
    ]
