# Generated by Django 5.0.6 on 2025-07-13 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_training_reminder', models.BooleanField(default=True)),
                ('notify_week_completion', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('site_notifications', models.BooleanField(default=True)),
                ('reminder_lead_time', models.IntegerField(choices=[(5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (30, '30 minutes')], default=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
