# Generated by Django 5.0.6 on 2025-07-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_exercises', models.ManyToManyField(blank=True, related_name='created_by_users', to='training.exercise')),
            ],
        ),
    ]
