# Generated by Django 5.0.6 on 2025-07-10 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontent',
            name='my_foods',
            field=models.ManyToManyField(blank=True, related_name='created_by_users', to='food.food'),
        ),
        migrations.AddField(
            model_name='usercontent',
            name='my_recipes',
            field=models.ManyToManyField(blank=True, related_name='created_by_users', to='food.recipe'),
        ),
        migrations.AddField(
            model_name='usercontent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_content', to=settings.AUTH_USER_MODEL),
        ),
    ]
